resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - secret.enc.yaml

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
