apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev   # <---- ADD THIS LINE
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
