apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-dev
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dev
  decryption:
    provider: sops
    secretRef:
      name: sops-age
