name: GitOps CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Kubernetes manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kube-linter
        run: |
          curl -sSL https://github.com/stackrox/kube-linter/releases/download/v0.6.7/kube-linter-linux.tar.gz | tar -xz
          sudo mv kube-linter /usr/local/bin/

      - name: Run kube-linter on base manifests
        run: kube-linter lint apps/base

      - name: Install kustomize
        run: |
          curl -s -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.1/kustomize_v5.4.1_linux_amd64.tar.gz | tar -xz
          sudo mv kustomize /usr/local/bin/

      - name: Validate Kustomize dev overlay
        run: |
          kustomize build apps/overlays/dev
